# Generated by Django 4.1.3 on 2022-11-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0003_remove_person_jobs_person_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='other_names',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
