# Generated by Django 4.1.3 on 2022-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0004_alter_person_other_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_channel', models.CharField(blank=True, max_length=150, null=True)),
                ('tv_channel_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
