# Generated by Django 4.1.3 on 2022-11-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0005_tvchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama_name', models.CharField(blank=True, max_length=200, null=True)),
                ('main_theme_img', models.ImageField(blank=True, null=True, upload_to='drama_themes')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('drama', 'Drama'), ('movie', 'Movie')], max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=900, null=True)),
                ('airing_dates_start', models.CharField(blank=True, max_length=100, null=True)),
                ('airing_dates_end', models.CharField(blank=True, max_length=100, null=True)),
                ('official_website', models.CharField(blank=True, max_length=150, null=True)),
                ('last_paragraph', models.TextField(blank=True, null=True)),
                ('casts', models.ManyToManyField(related_name='casts', to='dataclick.person')),
                ('directed_by', models.ManyToManyField(related_name='directors', to='dataclick.person')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='dataclick.genres')),
                ('tv_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataclick.tvchannel')),
                ('written_by', models.ManyToManyField(related_name='writters', to='dataclick.person')),
            ],
        ),
    ]
