# Generated by Django 4.1.3 on 2022-11-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0006_drama'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastOfDrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name_in_drama', models.CharField(blank=True, max_length=150, null=True)),
                ('extended_cast', models.BooleanField(default=False)),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataclick.person')),
            ],
        ),
        migrations.AddField(
            model_name='drama',
            name='extended_casts',
            field=models.ManyToManyField(related_name='extendedcasts', to='dataclick.castofdrama'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='casts',
            field=models.ManyToManyField(related_name='castsofdrama', to='dataclick.castofdrama'),
        ),
    ]
