# Generated by Django 4.1.3 on 2022-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0007_castofdrama_drama_extended_casts_alter_drama_casts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castofdrama',
            name='cast_name_in_drama',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
