# Generated by Django 4.1.3 on 2022-11-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0008_alter_castofdrama_cast_name_in_drama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castofdrama',
            name='cast_name_in_drama',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
