# Generated by Django 4.1.3 on 2022-11-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0009_alter_castofdrama_cast_name_in_drama'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='drama_images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataclick.drama')),
            ],
        ),
    ]
