# Generated by Django 4.1.3 on 2022-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0010_dramaimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='airing_dates_end',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='airing_dates_start',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='official_website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tvchannel',
            name='tv_channel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
