# Generated by Django 4.1.3 on 2022-11-30 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0011_alter_drama_airing_dates_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(blank=True, max_length=200, null=True)),
                ('main_theme_img', models.ImageField(blank=True, null=True, upload_to='movie_themes')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('other_names', models.CharField(blank=True, max_length=900, null=True)),
                ('airing_date', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
                ('last_paragraph', models.TextField(blank=True, null=True)),
                ('casts', models.ManyToManyField(related_name='casts_of_movie', to='dataclick.castofdrama')),
                ('directed_by', models.ManyToManyField(related_name='directors_of_movie', to='dataclick.person')),
                ('extended_casts', models.ManyToManyField(related_name='extendedcasts_of_movie', to='dataclick.castofdrama')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='dataclick.genres')),
                ('tv_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataclick.tvchannel')),
                ('written_by', models.ManyToManyField(related_name='writters_of_movie', to='dataclick.person')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='movie_images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataclick.movie')),
            ],
        ),
    ]
