# Generated by Django 4.1.3 on 2022-12-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0012_movie_movieimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tv_channel',
        ),
    ]
