# Generated by Django 4.1.3 on 2022-12-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0013_remove_movie_tv_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='drama_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
