# Generated by Django 4.1.3 on 2022-12-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0014_drama_drama_link_movie_movie_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='main_theme_img',
        ),
        migrations.RemoveField(
            model_name='dramaimages',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='main_theme_img',
        ),
        migrations.RemoveField(
            model_name='movieimages',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='personimages',
            name='image_file',
        ),
    ]
