# Generated by Django 4.1.3 on 2024-06-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0015_remove_drama_main_theme_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='work_type',
        ),
    ]
