# Generated by Django 4.1.3 on 2024-06-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataclick', '0016_remove_drama_work_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drama',
            options={'verbose_name': 'Drama'},
        ),
        migrations.AlterModelOptions(
            name='dramaimages',
            options={'verbose_name': 'Drama Image'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genre'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='tvchannel',
            options={'verbose_name': 'TV Channel'},
        ),
        migrations.RemoveField(
            model_name='drama',
            name='official_website',
        ),
    ]
